spring:
  datasource:
    url: jdbc:mysql://localhost:3306/littlerest?serverTimezone=GMT%2B8&characterEncoding=utf-8
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: w199972w

server:
  servlet:
    session:
      timeout: 7200s
    context-path: /LittleRest
