spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/littlerest?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: w199972w

server:
  servlet:
    session:
      timeout: 7200s
    context-path: /LittleRest
